# Generated by Django 5.2 on 2025-06-20 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('group_type', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GroupStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.IntegerField()),
                ('total_posts', models.IntegerField()),
                ('total_comments', models.IntegerField()),
                ('deleted_posts', models.IntegerField()),
                ('views', models.IntegerField()),
                ('status', models.CharField(blank=True, max_length=8, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('group', models.ForeignKey(on_delete=models.DO_NOTHING, to='stats.groups')),
            ],
            options={
                'db_table': 'group_statistics',
                'managed': False,
            },
        ),
    ]
