# Generated by Django 5.2 on 2025-07-21 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupstatistics',
            options={},
        ),
    ]
