# Generated by Django 5.2 on 2025-07-21 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_groupstatistics_group_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupstatistics',
            options={'managed': False},
        ),
    ]
